require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/user_event_preferences", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # UserEventPreference. As you add validations to UserEventPreference, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      UserEventPreference.create! valid_attributes
      get user_event_preferences_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      user_event_preference = UserEventPreference.create! valid_attributes
      get user_event_preference_url(user_event_preference)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_user_event_preference_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      user_event_preference = UserEventPreference.create! valid_attributes
      get edit_user_event_preference_url(user_event_preference)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new UserEventPreference" do
        expect {
          post user_event_preferences_url, params: { user_event_preference: valid_attributes }
        }.to change(UserEventPreference, :count).by(1)
      end

      it "redirects to the created user_event_preference" do
        post user_event_preferences_url, params: { user_event_preference: valid_attributes }
        expect(response).to redirect_to(user_event_preference_url(UserEventPreference.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new UserEventPreference" do
        expect {
          post user_event_preferences_url, params: { user_event_preference: invalid_attributes }
        }.to change(UserEventPreference, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post user_event_preferences_url, params: { user_event_preference: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested user_event_preference" do
        user_event_preference = UserEventPreference.create! valid_attributes
        patch user_event_preference_url(user_event_preference), params: { user_event_preference: new_attributes }
        user_event_preference.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the user_event_preference" do
        user_event_preference = UserEventPreference.create! valid_attributes
        patch user_event_preference_url(user_event_preference), params: { user_event_preference: new_attributes }
        user_event_preference.reload
        expect(response).to redirect_to(user_event_preference_url(user_event_preference))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        user_event_preference = UserEventPreference.create! valid_attributes
        patch user_event_preference_url(user_event_preference), params: { user_event_preference: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested user_event_preference" do
      user_event_preference = UserEventPreference.create! valid_attributes
      expect {
        delete user_event_preference_url(user_event_preference)
      }.to change(UserEventPreference, :count).by(-1)
    end

    it "redirects to the user_event_preferences list" do
      user_event_preference = UserEventPreference.create! valid_attributes
      delete user_event_preference_url(user_event_preference)
      expect(response).to redirect_to(user_event_preferences_url)
    end
  end
end
